# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
os: linux
dist: xenial

jobs:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5

before_install:
  - pip install -U pip setuptools wheel
install:
  - pip install -r requirements.txt 

script:
  - python -m unittest Tests.tests

