language: python
os: linux
dist: xenial
jobs:
  include:
  - python: 3.8
    env: BUILD=1
  - python: 3.7
  - python: 3.6
    env: TEST_TOX=1 
  - python: 3.5

before_install:
- pip install -U pip setuptools wheel
install:
- |
  if [ "${TEST_TOX:-}" != "" ]; then
    pip install -r requirements.txt codecov
  else
    pip install -r requirements.txt
  fi
script:
- |
  if [ "${BUILD:-}" != "" ]; then
    python setup.py sdist bdist_wheel
  fi
  python -m pip install . 
  if [ "${TEST_TOX:-}" != "" ]; then
    # tox does not use pyxpdf wheels, instead use sdist and
    # pyxpdf fails to build without '-std=c++14', Remove this when
    # either tox start using wheel for pyxpdf or pyxpdf can build without
    # '-std=c++14' hack.
    export CFLAGS='-std=c++14'
    python -m tox && codecov
  else
    pytest
  fi
before_deploy:
- |
  if [ "${BUILD:-}" != "" ]; then
    ls dist/
  fi


deploy:
  # Deploy on tags to GitHub Releases
  - provider: releases
    api_key:
      secure: V7I+468YdzwLhBU/PpfT8t9DHO3jw8kkZXHWRw5GEMAL+qK+VNLBSeui6/s+oeRYcOiaOVRmwWaygridgYdnumROj/rimPcZlIaVdgqKM8svMvB7GJ8hXbR5PDaR9pq+DyaNxAhbJPKkPrGGNpL/iEh/jP3SjzroEpTJgE53NRRncewuqV/gHuotEJ4nm50YI642EPmYydChhKPDEg+5xJJus4uUDqnC0fDU4MIYZQCdG5QNaVFYGHU0ds726HPHgHu6fik2vF0E9Fj29iX/KmDV0xwJAtSA/EGcFg8+AiaVUXe6WPfL1Cvv0n4QNc2H3tarJd2fH+d9a2h9Pby+SWj7yNWvbSB6yOnGacSjztAXyhljpk07vbbb8QcEnAjXwy8Z4qIznCDlmcGHZa6LmX4tKPZU1FFUYyosCKfuENlsBQtCXZDvcLOgt39vrn56+TqUUUqxorhigH5l7xBY8lw761k1kgAX7TbcL+I/5cS1MfMkm8EKrzhq6zpKGi0vsavFzThe9Q78xV2ueDFLTPf+ok1CjYyY3kAQn562dqr6DWgCCMwQqhTtLcjyzgi3DRp8JV8EaWF8u/Glc/bLB4QE9l5ksrRUATQF5lXYbZD+Gm9aoAbR5fsCEitUQ6ELGGd+lqRSjA6nCgL4gTjxcjkLB7u0LGk0Akk63W5QNZM=
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: ashutoshvarma/ggsipu_result
      tags: true
      condition: $BUILD


  # Deploy master non-tags to test PyPI
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: ygSrvYz8rd9mC97TZt7aQ1g+sSfQFpp0NMBZJojHsItN1cpJnUlBNdNO7ctnAPEbDSZP8hd5ZHoBxtTphvZTAXm4ohHsSXam2u1asaBaOX57qVjG/ggjT2uQt4fgAA1S5dzROXKqpunkh2lJzjURO+wAhrf/MmWZtdlnbifU5JlDFJTH8vOg++vJOQ1ZKzvhdiy3spoGlYS0wDrkvUM0daiqg/dCs/p/7i8ESywmFzCg1xbBEoDd/VnFZMo7Cdq8ctt+vMFb95JWiFQAwr3iu9CB33V+sUR1cA0nywGI08pVoyP53kuFjCTDGbxI/5pIebqxC71HZRIHXVUd8CR0XItLq1t8rIYVglufDmk8RGW5wLHp/8ttKKg9rDFikouC1H2cxjS8v9BEY3T15+DWii/41QlI4L8Zj6m7ZhHxYQlMOIRK0YdPYfhVzHFOeAhr3odo0Re1UUbbpsWM9ukgSjvcO/Py7GUISjicUAiHyhNcFY2J5LgTGd5BwLFAMHxLFJfs14icUXcmto7xyjhZ0i+etAaIyaoUwpn3WuVHPaq7vWGfpvDezu4ruUXFZ+MUK0bZsCHR35B6J3nLin5QNBD+O+JbRBDD7UvU1nIZirfSMzl7nqT1tlhv4Rq7UesUCuudNDp5zgi5P1w0EdZBa6ZEY1vPUSJznS1s7Z1+HGY=
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ashutoshvarma/ggsipu_result
      tags: false
      branch: master
      condition: $BUILD


  # Deploy on tags to PyPI
  - provider: pypi
    user: __token__
    password:
      secure: 01FHsF5jSnwooNrS14t5/YGJn8xCfXZuXCamLSZZfvUzMhJiRcWnpIDpOnDZkYfC7fTjQGbKlVukTaCyhTgRJnYR7dmuw7a0bQUbRuGk+HXtTb9eGONkl2kfa5LD7aBXcDQJKbxRxDr5GGfJdbFFbAPNHFlnRrEuK4GgYhcQKs/LeXbxXPaXmkbmSlhm3yAYLv/BAdqdV3Iq/gek3XkjmvYTbPrp28swlgDaZ7ghhrGI6B1DujKjp2MWH4DRKV8gv2IAXtb1aC88vU+APYD+rg5zmfuCY4w3ZhI/mBOQIrzGR3ZuPG8fsTZ3BK4Smp4ZV7lqu0wmkInEgE8EjRhm0HmHBoOFIVyFJIj0s4xwYlA0fEMCkAZSbW+yYyXJ7A1tpZMw5S/bAFcjAoaAuOxyuohA40raffI0Vo88vidi16kZhNy0fOKZSkinV5JQCGCcyhxSO53MlaleA1ICvtcZL+QSTSh9Zq1ARCW8mpNKqeegKJL96+93/aL3Q8Uvl98ZPZKyuWKeiUKreuKr9Q2oRCYMLsrue2TXDigbnUr/6sumLwFz4WMul6qzTOi1piw2ffUKubTki5yC4HDne5+ul+DmygcNWTvjn+iTg+FHfUYPqAb3KBWX49UmLUMjrTwY95cPpLj96qvi/6wGDV6Mqikw0au50sdAYS4YSjgyFWs=
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      repo: ashutoshvarma/ggsipu_result
      tags: true
      condition: $BUILD
